### ISSUE TITLE
Off Topic And Curious 

### ISSUE THREAD

**Issue by mathi-vignesh** [anotherduckling/anotherduckling#1]
How Did You Created Your Website..? 
ducklink.pages.dev
freemediaheckyeah.pages.dev

The Template/ UI And UX is Awesome.
May I Know How Can I Create Like That?
Please Guide Me. 
I Saw Around 5 Websites Similarly

**Comment by anotherduckling** [comment]
LOL. Sorry for the very late reply. I didn't notice there was an issue posted. Anyway... So I am using [Retype](https://retype.com/). It's pretty cool. You write the markdown file and it generates the html files and uses it as the source code for the sites. The docs of retype explains everything. You can visit https://wotaku.pages.dev/. I am actively working on that project.  I formatted the fmhy site but the whole thing is maintained by the fmhy org.
